email: info@ziakurtos.com
instagram_url: https://www.instagram.com/ziakurtos/
facebook_url: https://www.facebook.com/zia.kurtos/
tiktok_url: https://www.tiktok.com/@zia_kurtos
active_theme: summer
main_cta_label: Découvrir nos kürtös artisanaux
contact_cta_label: Inviter Zia Kürtös
announcement_text: null
footer_credit_text: Site créé par Web On It !
footer_credit_url: https://www.instagram.com/web.onit/
